import { Component, OnInit } from '@angular/core';
import { ActivatedRoute, Router, Params } from '@angular/router';
import {
  FormGroup,
  FormControl,
  Validators,
  FormBuilder,
  FormArray,
  ValidatorFn,
} from '@angular/forms';
import { AppService } from '../app.component.service';
import { CommonFunctionsService } from '../sheared';
import { ToastrService } from 'ngx-toastr';

@Component({
  selector: 'app-candidate-signup-education',
  templateUrl: './candidate-signup-education.component.html',
  styleUrls: ['./candidate-signup-education.component.css'],
})
export class CandidateSignupEducationComponent implements OnInit {
  signupEducationForm: FormGroup;
  arrayItems = [];
  courses;
  items = [];
  specializations;
  uniqueId;
  education = [];
  courseTypes;
  fresher = true;
  disableLink = false;
  colleges;
  skills = [];
  below10 = true;

  Years = [
    { value: '1981' },
    { value: '1982' },
    { value: '1983' },
    { value: '1984' },
    { value: '1985' },
    { value: '1986' },
    { value: '1987' },
    { value: '1988' },
    { value: '1989' },
    { value: '1990' },
    { value: '1991' },
    { value: '1992' },
    { value: '1993' },
    { value: '1994' },
    { value: '1995' },
    { value: '1996' },
    { value: '1997' },
    { value: '1998' },
    { value: '1999' },
    { value: '2000' },
    { value: '2001' },
    { value: '2002' },
    { value: '2003' },
    { value: '2004' },
    { value: '2005' },
    { value: '2006' },
    { value: '2007' },
    { value: '2008' },
    { value: '2009' },
    { value: '2010' },
    { value: '2011' },
    { value: '2012' },
    { value: '2013' },
    { value: '2014' },
    { value: '2015' },
    { value: '2016' },
    { value: '2017' },
    { value: '2018' },
    { value: '2019' },
  ];

  qualificationsArray = [
    [
      { value: 'Doctrate PHD' },
      { value: 'Masters/Post Graduation' },
      { value: 'Graduation/Diploma' },
      { value: '12th' },
      { value: '10th' },
      { value: 'Below 10th' },
    ],
  ];
  constructor(
    private formBuilder: FormBuilder,
    private router: Router,
    private route: ActivatedRoute,
    private toaster: ToastrService,
    private appService: AppService
  ) {
    this.route.params.subscribe((params: Params) => {
      this.uniqueId = params.id;
    });
  }
  ngOnInit() {
    this.userTypeFind(localStorage.getItem('TypeUser'));

    console.log('asdasdasdsd');
    this.signupEducationForm = this.formBuilder.group({
      skills: new FormControl('', []),
      education: this.formBuilder.array([]),
    });
    this.addfieldsFormGroup();

    this.courses = {
      'Doctrate PHD': [
        { value: 'Ph.D/Doctorate' },
        { value: 'MPHIL' },
        { value: 'other' },
      ],
      'Masters/Post Graduation': [
        { value: 'CA' },
        { value: 'CS' },
        { value: 'DM' },
        { value: 'ICWA' },
        { value: 'Integrated PG' },
        { value: 'LLM' },
        { value: 'M.A' },
        { value: 'M.Arch' },
        { value: 'M.Ch' },
        { value: 'M.COM' },
        { value: 'M.Des.' },
        { value: 'M.Ed' },
        { value: 'M.Pharma' },
        { value: 'MS/M.Sc(Science)' },
        { value: 'M.Tech' },
        { value: 'MBA/PGDM' },
        { value: 'MCA' },
        { value: 'MCM' },
        { value: 'MDS' },
        { value: 'MFA' },
        { value: 'Medical-MS/MD' },
        { value: 'MVSC' },
        { value: 'PG Diploma' },
        { value: 'other' },
      ],
      'Graduation/Diploma': [
        { value: 'B.A' },
        { value: 'B.Arch' },
        { value: 'B.B.A/B.M.S' },
        { value: 'B.Com' },
        { value: 'B.Des.' },
        { value: 'B.Ed' },
        { value: 'B.EI.Ed' },
        { value: 'B.p.Ed' },
        { value: 'B.Pharma' },
        { value: 'B.Sc'},
        { value: 'B.Tech/BE' },
        { value: 'B.U.M.S' },
        { value: 'BAMS' },
        { value: 'BCA' },
        { value: 'BFA' },
        { value: 'BHM' },
        { value: 'BHMS' },
        { value: 'BVSC' },
        { value: 'Diploma' },
        { value: 'LLB' },
        { value: 'MBBS' },
        { value: 'Other' },
      ],
      '12th': [
        { value: 'BOARD' },
        { value: 'All India' },
        { value: 'CBSE' },
        { value: 'CISCE(ICSE/ISC)' },
        { value: 'Diploma' },
        { value: 'National Open School' },
        { value: 'IB(International Baccalaureate)' },
        { value: 'STATE BOARD' },
        { value: 'Andhra Pradesh' },
        { value: 'Assam' },
        { value: 'Bihar' },
        { value: 'Goa' },
        { value: 'Gujrat' },
        { value: 'Haryana' },
        { value: 'J & K' },
        { value: 'Karnataka' },
        { value: 'Kerala' },
        { value: 'Maharastra' },
        { value: 'Madhya Pradesh' },
        { value: 'Manipur' },
        { value: 'Meghalaya' },
        { value: 'Mizoram' },
        { value: 'Nagaland' },
        { value: 'Orissa' },
        { value: 'Punjab ' },
        { value: 'Rajasthan' },
        { value: 'Tamil Nadu' },
        { value: 'Tirpura' },
        { value: 'Uttar Pradesh' },
        { value: 'West Bengal' },
        { value: 'Other' },
      ],
      '10th': [
        { value: 'BOARD' },
        { value: 'All India' },
        { value: 'CBSE' },
        { value: 'CISCE(ICSE/ISC)' },
        { value: 'Diploma' },
        { value: 'National Open School' },
        { value: 'IB(International Baccalaureate)' },
        { value: 'STATE BOARD' },
        { value: 'Andhra Pradesh' },
        { value: 'Assam' },
        { value: 'Bihar' },
        { value: 'Goa' },
        { value: 'Gujrat' },
        { value: 'Haryana' },
        { value: 'J & K' },
        { value: 'Karnataka' },
        { value: 'Kerala' },
        { value: 'Maharastra' },
        { value: 'Madhya Pradesh' },
        { value: 'Manipur' },
        { value: 'Meghalaya' },
        { value: 'Mizoram' },
        { value: 'Nagaland' },
        { value: 'Orissa' },
        { value: 'Punjab ' },
        { value: 'Rajasthan' },
        { value: 'Tamil Nadu' },
        { value: 'Tirpura' },
        { value: 'Uttar Pradesh' },
        { value: 'West Bengal' },
        { value: 'Other' },
      ],
      'Below 10th': [{ value: 'Below 10th' }],
    };
    this.specializations = {
      'B.A': [
        { value: 'Arts&Humanities' },
        { value: 'Communication ' },
        { value: 'Economics' },
        { value: 'English' },
        { value: 'Film' },
        { value: 'Fine arts' },
        { value: 'Hindi' },
        { value: 'History' },
        { value: 'Hotel Management' },
        { value: 'Journalism' },
        { value: 'Maths' },
        { value: 'Pass Course' },
        { value: 'Political Science' },
        { value: 'PR/Advertising' },
        { value: 'Psychology' },
        { value: 'Sanskrit' },
        { value: 'Sociology ' },
        { value: 'Statistics ' },
        { value: 'Vocational Course' },
        { value: 'Other' },
      ],
      'B.Arch': [{ value: 'Architecture' }, { value: 'Other' }],
      'B.B.A/B.M.S': [{ value: 'Management' }, { value: 'Other' }],
      'B.Com': [{ value: 'Commerce' }, { value: 'Other' }],
      'B.Des.': [
        { value: 'Animation Film Design' },
        { value: 'Ceramic & Glass Design' },
        { value: 'Exhibition Design' },
        { value: 'Film and Video Communication' },
        { value: 'Furniture Design' },
        { value: 'Graphic Design' },
        { value: 'Product Design' },
        { value: 'Textile Design' },
        { value: 'Other' },
      ],
      'B.Ed': [{ value: 'Education' }, { value: 'Other' }],
      'B.EI.Ed': [{ value: 'Elementary Education' }, { value: 'Other' }],
      'B.p.Ed': [{ value: 'Physical Education' }, { value: 'Other' }],
      'B.Pharma': [{ value: 'Pharmacy' }, { value: 'Other' }],
      'B.Tech/BE': [
        { value: 'Agriculture ' },
        { value: 'Anthropology' },
        { value: 'Bio-Chemistry' },
        { value: 'Biology' },
        { value: 'Botany ' },
        { value: 'Chemistry' },
        { value: 'Computers' },
        { value: 'Dairy Technology' },
        { value: 'Electronics' },
        { value: 'Environmental Science' },
        { value: 'Food Technology ' },
        { value: 'General' },
        { value: 'Geology' },
        { value: 'Home Science' },
        { value: 'Hospitality and Hotel Management' },
        { value: 'Maths' },
        { value: 'Microbiology' },
        { value: 'Nursing ' },
        { value: 'Optometry' },
        { value: 'Physics ' },
        { value: 'Statistics' },
        { value: 'Zoology ' },
        { value: 'Other' },
      ],
      'B.U.M.S': [{ value: 'Unani Medicine' }, { value: 'Other' }],
      BAMS: [{ value: 'Ayurveda' }, { value: 'Other' }],
      BCA: [{ value: 'Computers' }, { value: 'Other' }],
      BFA: [{ value: 'Dentistry' }, { value: 'Other' }],
      BHM: [
        { value: 'Art History' },
        { value: 'Painting' },
        { value: 'Printmaking' },
        { value: 'Sculpture' },
        { value: 'Visual Communication' },
        { value: 'Other' },
      ],
      BHMS: [{ value: 'Hotel Management' }, { value: 'Other' }],
      BVSC: [{ value: 'Veterinary Science' }, { value: 'Other' }],
      Diploma: [
        { value: 'Architecture' },
        { value: 'Chemical' },
        { value: 'Civil' },
        { value: 'Computers' },
        { value: 'Electrical' },
        { value: 'Electronics/Telecommunication ' },
        { value: 'Engineering' },
        { value: 'Export/Import' },
        { value: 'Fashion Designing/Other Designing' },
        { value: 'Graphic/Web Designing' },
        { value: 'Hotel Management' },
        { value: 'Insurance' },
        { value: 'Management' },
        { value: 'Mechanical' },
        { value: 'Tourism' },
        { value: 'vISUAL Arts' },
        { value: 'Vocational Course' },
        { value: 'Other' },
      ],
      LLB: [{ value: 'Law' }, { value: 'Other' }],
      MBBS: [{ value: 'Medicine' }, { value: 'Other' }],

      'M.Arch': [{ value: 'Architecture' }, { Other: 'Other' }],
      'M.Ch': [
        { value: 'Burns & Plastic Surgery' },
        { value: 'Cardio Thoracic and Vascular Surgery' },
        { value: 'Cardio Thoracic Surgery' },
        { value: 'Endocrine Surgery' },
        { value: 'Gynaecological Oncology' },
        { value: 'Hand & Micro Surgery' },
        { value: 'Hand Surgery' },
        { value: 'Hepato Pancreato Biliary Surgery' },
        { value: 'Neuro Surgery' },
        { value: 'Oncology' },
        { value: 'Pediatric Cardio-Thoracic Vascular Surgery' },
        { value: 'Pediatric Surgery' },
        { value: 'Plastic & Reconstructive Surgery' },
        { value: 'Plastic Surgery' },
        { value: 'Surgical Gastroenterology/G.I.Surgery' },
        { value: 'Surgical Oncology' },
        { value: 'Thoracic Surgery' },
        { value: 'Urology' },
        { value: 'Urology/Genito-Urinary Surgery' },
        { value: 'Vascular Surgery' },
        { value: 'Other' },
      ],
      'M.COM': [{ value: 'Commerce' }, { value: 'Other' }],
      'M.Des.': [
        { value: '' },
        { value: 'Animation Film Design' },
        { value: 'Apparel Design' },
        { value: 'Ceramic & Glass Design' },
        { value: 'Design for Retail Experience' },
        { value: 'Digital Game Design' },
        { value: 'Film and Video Communication' },
        { value: 'Furniture Design' },
        { value: ' Graphic Design' },
        { value: 'Information Design' },
        { value: 'Interaction Design' },
        { value: 'Lifestyle Accessory Design' },
        { value: 'New Medio Design' },
        { value: 'Photography Design' },
        { value: 'Product Design' },
        { value: 'Strategic Design Management' },
        { value: 'Textile Design' },
        { value: 'Toy & Game Design' },
        { value: 'Transportation & Automobile Design' },
        { value: 'Universal Design' },
        { value: 'Other' },
      ],
      'M.Ed': [{ value: 'Education' }, { value: 'other' }],
      'M.Pharma': [{ value: 'Pharmacy' }, { value: 'other' }],
      'MS/M.Sc(Science)': [
        { value: 'Aerospace & Mechanical Engineering' },
        { value: 'Agriculture' },
        { value: 'Anthropology' },
        { value: 'Astronautical Engineering' },
        { value: 'Bio-Chemistry' },
        { value: 'Biology' },
        { value: 'Biotechnology' },
        { value: 'Botany' },
        { value: 'Chemical Engineering & Materials Science' },
        { value: 'Chemistry' },
        { value: 'Civil & Environmental Engineering' },
        { value: 'Computer' },
        { value: 'Cyber Security Engineering' },
        { value: 'Dairy Technology' },
        { value: 'Data Informatics' },
        { value: 'Electrical Engineering' },
        { value: 'Electronics' },
        { value: 'Electronics & Embedded Technology' },
        { value: 'Environmental Science' },
        { value: 'Food Technology' },
        { value: 'Geology' },
        { value: 'Home Science' },
        { value: 'Hospitality Administration' },
        { value: 'Industrial & Systems Engineering' },
        { value: 'Marine Engineering' },
        { value: 'Maths' },
        { value: 'Mechanical Engineering' },
        { value: 'Mechatronics' },
        { value: 'Microbiology' },
        { value: 'Nursingv' },
        { value: 'Optometry' },
        { value: 'Organic Chemistry' },
        { value: 'Petroleum Engineering' },
        { value: 'Physics' },
        { value: 'Statistics' },
        { value: 'Systems Architecting and Engineering' },
        { value: 'Veterinary Science' },
        { value: 'Zoology' },
        { value: 'Other' },
      ],
      'B.Sc': [
        { value: 'Aerospace & Mechanical Engineering' },
        { value: 'Agriculture' },
        { value: 'Anthropology' },
        { value: 'Astronautical Engineering' },
        { value: 'Bio-Chemistry' },
        { value: 'Biology' },
        { value: 'Biotechnology' },
        { value: 'Botany' },
        { value: 'Chemical Engineering & Materials Science' },
        { value: 'Chemistry' },
        { value: 'Civil & Environmental Engineering' },
        { value: 'Computer' },
        { value: 'Cyber Security Engineering' },
        { value: 'Dairy Technology' },
        { value: 'Data Informatics' },
        { value: 'Electrical Engineering' },
        { value: 'Electronics' },
        { value: 'Electronics & Embedded Technology' },
        { value: 'Environmental Science' },
        { value: 'Food Technology' },
        { value: 'Geology' },
        { value: 'Home Science' },
        { value: 'Hospitality Administration' },
        { value: 'Industrial & Systems Engineering' },
        { value: 'Marine Engineering' },
        { value: 'Maths' },
        { value: 'Mechanical Engineering' },
        { value: 'Mechatronics' },
        { value: 'Microbiology' },
        { value: 'Nursingv' },
        { value: 'Optometry' },
        { value: 'Organic Chemistry' },
        { value: 'Petroleum Engineering' },
        { value: 'Physics' },
        { value: 'Statistics' },
        { value: 'Systems Architecting and Engineering' },
        { value: 'Veterinary Science' },
        { value: 'Zoology' },
        { value: 'Other' },
      ],
      'M.Tech': [
        { value: 'Agriculture' },
        { value: 'Automobile' },
        { value: 'Aviation' },
        { value: 'Bio-Chemistry/Bio-Technology' },
        { value: 'Biomedical' },
        { value: 'Ceramics' },
        { value: 'Chemical' },
        { value: 'Civil' },
        { value: 'Computers' },
        { value: 'Electrical' },
        { value: 'Electronics/Telecommunication' },
        { value: 'Energy' },
        { value: 'Environmental' },
        { value: 'Instrumentation' },
        { value: 'Marine' },
        { value: 'Mechanical' },
        { value: 'Metallurgy' },
        { value: 'Mineral' },
        { value: 'Mining' },
        { value: 'Nuclear' },
        { value: 'Other Engineering' },
        { value: 'Paint/Oil' },
        { value: 'Petroleum' },
        { value: 'Plastics' },
        { value: 'Production/Industrial' },
        { value: 'Textile' },
        { value: 'Other' },
      ],
      'MBA/PGDM': [
        { value: 'Advertising/Mass Communication' },
        { value: 'Finance' },
        { value: 'Hospitality Management' },
        { value: 'HR/Industrial Relations' },
        { value: 'Information Technology' },
        { value: 'International Business' },
        { value: 'Marketing' },
        { value: 'Operations' },
        { value: 'Other Management' },
        { value: 'Systems' },
        { value: 'Other' },
      ],
      MCA: [{ value: 'COMPUTERS' }, { value: 'Other' }],
      MCM: [{ value: 'Computers and Management' }, { value: 'Other' }],
      MDS: [{ value: 'Dentistry' }, { value: 'Other' }],
      MFA: [
        { value: 'Printmaking' },
        { value: 'Sculpture' },
        { value: 'Visual Communication' },
        { value: 'Other' },
      ],
      'Medical-MS/MD': [
        { value: 'Anaesthesiology' },
        { value: 'Anatomy' },
        { value: 'Aviation Medicine/Aerospace Medicine' },
        { value: 'Ayurveda' },
        { value: 'Bio-Chemistry' },
        { value: 'Bio-Physics' },
        { value: 'Blood Banking & Immuno. Haem/Imm & Blood Trans' },
        { value: 'Cardiology' },
        { value: 'CCM' },
        { value: 'Dermatology' },
        { value: 'Emergency Medicine' },
        { value: 'ENT' },
        { value: 'Forensic Medicine/Forensic Medicine & Toxicology' },
        { value: 'General Practitioner' },
        { value: 'General Surgery' },
        { value: 'Geriatrics' },
        { value: 'Gyneocology' },
        { value: 'Health Administration' },
        { value: 'Hepatology' },
        { value: 'Hospital Administration' },
        { value: 'Immunology' },
        { value: 'Leb Medicine' },
        { value: 'Maternity & Child Health' },
        { value: 'Medical Genetics' },
        { value: 'Microbiology' },
        { value: 'Neonatal' },
        { value: 'Nephrology' },
        { value: 'Neuro Surgery' },
        { value: 'Nuclear Medicine' },
        { value: 'Obstretrics' },
        { value: 'Oncology' },
        { value: 'Opthalmology' },
        { value: 'Orthopaedic' },
        { value: 'P.S.M' },
        { value: 'Palliative Medicine' },
        { value: 'Pathology' },
        { value: 'Pediatrics' },
        { value: 'Pharmacology' },
        { value: 'Physical Medicine & Rehabilitation' },
        { value: 'Psychiatry' },
        { value: 'Psychology' },
        { value: 'Public Health (Epidemiology)' },
        { value: 'Pulmonary Medicine' },
        { value: 'R&d' },
        { value: 'Radiology' },
        { value: 'Radiotherapy' },
        { value: 'Rheumatology' },
        { value: 'Social & Preventive Medicine/ Community Medicine' },
        { value: 'Sports Medicine' },
        { value: 'Thoracic Medicine' },
        { value: 'Traumatology and Surgery' },
        { value: 'Tropical Medicine' },
        { value: 'Tuberculosis & Respiratory Diseases/ Pulmonary Medicine' },
        { value: 'Unani' },
        { value: 'Urology' },
        { value: 'Venereology' },
        { value: 'Other' },
      ],
      MVSC: [{ value: 'Veterinary Science' }, { value: 'Other' }],
      'PG Diploma': [
        { value: 'Chemical' },
        { value: 'Civil' },
        { value: 'Computers' },
        { value: 'Electrical' },
        { value: 'Electronics' },
        { value: 'Mechanical' },
        { value: 'Other' },
      ],
      LLM: [{ value: 'LLM' }, { value: 'other' }],
      'M.A': [
        { value: 'Anthropology' },
        { value: 'Arts & Humanities' },
        { value: 'Communication ' },
        { value: 'Economics' },
        { value: 'English' },
        { value: 'Film' },
        { value: 'Fine arts' },
        { value: 'Hindi' },
        { value: 'History' },
        { value: 'Journalism' },
        { value: 'Maths' },
        { value: 'Political Science' },
        { value: 'PR/Advertising' },
        { value: 'Psychology' },
        { value: 'Sanskritv' },
        { value: 'Sociology' },
        { value: 'Statistics' },
        { value: 'Other' },
      ],
      'Integrated PG': [
        { value: 'Journalism/Mass Communication' },
        { value: 'Management' },
        { value: 'PR/Advertising' },
        { value: 'Tourism' },
        { value: 'Other' },
      ],
      ICWA: [{ value: 'ICWA (CMA)' }, { value: 'other' }],
      other: [{ value: 'other' }],
      CA: [
        { value: 'CA' },
        { value: 'First Attempt ' },
        { value: 'Pursuing' },
        { value: 'Second Attempt' },
        { value: 'Other' },
      ],
      CS: [{ value: 'CS' }, { value: 'other' }],
      DM: [
        { value: 'Cardiac-Anaes' },
        { value: 'Cardiology' },
        { value: 'Child & Adolescent Psychiatry' },
        { value: 'Clinical haematology' },
        { value: 'Clinical immunology' },
        { value: 'Clinical Pharmacology' },
        { value: 'Critical Care Medicine' },
        { value: 'Endocrinology' },
        { value: 'Gastroenterology' },
        { value: 'Geriatric Mental Health' },
        { value: 'Haematology Pathology' },
        { value: 'Hepatology' },
        { value: 'Immunology' },
        { value: 'Infectious Diseases' },
        { value: 'Medical Genetics' },
        { value: 'Neonatology' },
        { value: 'Nephrology' },
        { value: 'Neuro Anaesthesia' },
        { value: 'Neuro Radiology' },
        { value: 'Neurology' },
        { value: 'Oncology' },
        { value: 'Organ Transplant Anaesthesia & Critical Care' },
        { value: 'Pediatric Anaesthesia' },
        { value: 'Pediatric Cardiology' },
        { value: 'Pediatric Gastroenterology' },
        { value: 'Pediatric Hepatology' },
        { value: 'Pediatric Nephrology' },
        { value: 'Pediatric Oncology' },
        { value: 'Pulmonary Med & Critical Care Med' },
        { value: 'Pulmonary Medicine' },
        { value: 'Reproductive Medicine' },
        { value: 'Rheumatology' },
        { value: 'Virology' },
        { value: 'Other' },
      ],
      MPHIL: [
        { value: 'Advertising/Mass Communication' },
        { value: 'Agriculture ' },
        { value: 'Anthropology ' },
        { value: 'Architecture ' },
        { value: 'Arts & Humanities ' },
        { value: 'Astrophysics ' },
        { value: 'Automobile ' },
        { value: 'Aviation ' },
        { value: 'Bio-Chemistry/Bio-Technology ' },
        { value: 'Biomedical ' },
        { value: 'Biophysics ' },
        { value: 'Biotechnology ' },
        { value: 'Botany ' },
        { value: 'Ceramics' },
        { value: 'Chemical ' },
        { value: 'Chemistry ' },
        { value: 'Civil ' },
        { value: 'Commerce' },
        { value: 'Communication' },
        { value: 'Computers ' },
        { value: 'Dairy Technology' },
        { value: 'Dermatology ' },
        { value: 'Economics ' },
        { value: 'Education ' },
        { value: 'Electrical ' },
        { value: 'Electronics/Telecommunication ' },
        { value: 'Energy ' },
        { value: 'ENT ' },
        { value: 'Environmental ' },
        { value: 'Fashion Designing/Other Designing ' },
        { value: 'Film ' },
        { value: 'Finance' },
        { value: 'Fine arts' },
        { value: 'Food Technology' },
        { value: 'Genetics ' },
        { value: 'History ' },
        { value: 'Home Science' },
        { value: 'Hotel Management' },
        { value: 'HR/Industrial Relations ' },
        { value: 'Immunology ' },
        { value: 'Instrumentation' },
        { value: ' International Business' },
        { value: ' Journalism ' },
        { value: 'Law ' },
        { value: 'Linguistics' },
        { value: 'Literature ' },
        { value: 'Marine ' },
        { value: 'Marketing' },
        { value: 'Maths ' },
        { value: 'Mechanical' },
        { value: 'Medicine' },
        { value: 'Metallurgy' },
        { value: 'Microbiology' },
        { value: 'Mineral ' },
        { value: 'Mining ' },
        { value: 'Music ' },
        { value: 'Neonatal' },
        { value: 'Nuclear ' },
        { value: 'Nursing ' },
        { value: 'Obstetrics' },
        { value: 'Other Arts ' },
        { value: 'Other Doctorate ' },
        { value: 'Other Engineering' },
        { value: 'Other Management ' },
        { value: 'Other Science ' },
        { value: 'Paint/Oil ' },
        { value: 'Pathology ' },
        { value: 'Pediatrics ' },
        { value: 'Petroleum ' },
        { value: 'Pharmacy ' },
        { value: 'Philosophy' },
        { value: 'Physical Education ' },
        { value: 'Physics ' },
        { value: 'Plastics ' },
        { value: 'Political Science ' },
        { value: 'Production/Industrial' },
        { value: 'Psychiatry ' },
        { value: 'Psychology ' },
        { value: 'Radiology ' },
        { value: 'Rheumatology' },
        { value: 'Sanskrit ' },
        { value: 'Sociology ' },
        { value: 'Special Education' },
        { value: 'Statistics ' },
        { value: 'Systems ' },
        { value: 'Textile ' },
        { value: 'Vocational Courses ' },
        { value: 'Zoology' },
        { value: 'Other ' },
      ],
      'Ph.D/Doctorate': [
        { value: 'Advertising/Mass Communication' },
        { value: 'Agriculture ' },
        { value: 'Anthropology ' },
        { value: 'Architecture ' },
        { value: 'Arts & Humanities ' },
        { value: 'Astrophysics ' },
        { value: 'Automobile ' },
        { value: 'Aviation ' },
        { value: 'Bio-Chemistry/Bio-Technology ' },
        { value: 'Biomedical ' },
        { value: 'Biophysics ' },
        { value: 'Biotechnology ' },
        { value: 'Botany ' },
        { value: 'Ceramics' },
        { value: 'Chemical ' },
        { value: 'Chemistry ' },
        { value: 'Civil ' },
        { value: 'Commerce' },
        { value: 'Communication' },
        { value: 'Computers ' },
        { value: 'Dairy Technology' },
        { value: 'Dermatology ' },
        { value: 'Economics ' },
        { value: 'Education ' },
        { value: 'Electrical ' },
        { value: 'Electronics/Telecommunication ' },
        { value: 'Energy ' },
        { value: 'ENT ' },
        { value: 'Environmental ' },
        { value: 'Fashion Designing/Other Designing ' },
        { value: 'Film ' },
        { value: 'Finance' },
        { value: 'Fine arts' },
        { value: 'Food Technology' },
        { value: 'Genetics ' },
        { value: 'History ' },
        { value: 'Home Science' },
        { value: 'Hotel Management' },
        { value: 'HR/Industrial Relations ' },
        { value: 'Immunology ' },
        { value: 'Instrumentation' },
        { value: ' International Business' },
        { value: ' Journalism ' },
        { value: 'Law ' },
        { value: 'Linguistics' },
        { value: 'Literature ' },
        { value: 'Marine ' },
        { value: 'Marketing' },
        { value: 'Maths ' },
        { value: 'Mechanical' },
        { value: 'Medicine' },
        { value: 'Metallurgy' },
        { value: 'Microbiology' },
        { value: 'Mineral ' },
        { value: 'Mining ' },
        { value: 'Music ' },
        { value: 'Neonatal' },
        { value: 'Nuclear ' },
        { value: 'Nursing ' },
        { value: 'Obstetrics' },
        { value: 'Other Arts ' },
        { value: 'Other Doctorate ' },
        { value: 'Other Engineering' },
        { value: 'Other Management ' },
        { value: 'Other Science ' },
        { value: 'Paint/Oil ' },
        { value: 'Pathology ' },
        { value: 'Pediatrics ' },
        { value: 'Petroleum ' },
        { value: 'Pharmacy ' },
        { value: 'Philosophy' },
        { value: 'Physical Education ' },
        { value: 'Physics ' },
        { value: 'Plastics ' },
        { value: 'Political Science ' },
        { value: 'Production/Industrial' },
        { value: 'Psychiatry ' },
        { value: 'Psychology ' },
        { value: 'Radiology ' },
        { value: 'Rheumatology' },
        { value: 'Sanskrit ' },
        { value: 'Sociology ' },
        { value: 'Special Education' },
        { value: 'Statistics ' },
        { value: 'Systems ' },
        { value: 'Textile ' },
        { value: 'Vocational Courses ' },
        { value: 'Zoology' },
        { value: 'Other ' },
      ],
      'Graduation/Diploma': [{ value: 'Graduation/Diploma' }],
      '12th': [{ value: '12th' }],
      '10th': [{ value: '10th' }],
      'Below 10th': [{ value: 'Below 10th' }],
    };
    this.colleges = [
      { value: 'A. V. C. College, Nagapattinam ' },
      { value: 'Abhilashi University' },
      { value: 'Acharya N.G. Ranga Agricultural University' },
      { value: 'Acharya Nagarjuna University' },
      { value: 'Acharya Narendra Dev College, New Delhi ' },
      { value: 'Adamas University' },
      { value: 'Adesh University' },
      { value: 'Adikavi Nannaya University' },
      { value: 'Ahmedabad University' },
      { value: 'AISECT University' },
      { value: 'Ajeenkya D.Y. Patil University' },
      { value: 'Akal University' },
      { value: 'AKS University' },
      { value: 'Al-Falah University' },
      { value: 'Alagappa University' },
      { value: 'Aliah University' },
      { value: 'Aligarh Muslim University' },
      { value: 'All India Institute of Medical Sciences Bhopal' },
      { value: 'All India Institute of Medical Sciences Bhubaneswar' },
      { value: 'All India Institute of Medical Sciences Delhi' },
      { value: 'All India Institute of Medical Sciences Jodhpur' },
      { value: 'All India Institute of Medical Sciences Patna' },
      { value: 'All India Institute of Medical Sciences Raipur' },
      { value: 'All India Institute of Medical Sciences Rishikesh' },
      { value: 'Allahabad State University' },
      { value: 'Alliance University' },
      { value: 'Ambedkar University Delhi' },
      { value: 'Amity University' },
      { value: 'Amrita Vishwa Vidyapeetham' },
      { value: 'Anand Agricultural University' },
      { value: 'Anant National University' },
      { value: 'Andhra Loyola College, Vijayawada' },
      { value: 'Andhra University' },
      { value: 'Anna Adarsh College for Women, Chennai ' },
      { value: 'Anna University' },
      { value: 'Annamalai University' },
      { value: 'Ansal University' },
      { value: 'AP Goyal Shimla University' },
      { value: 'Apeejay Stya University' },
      { value: 'Apex Professional University' },
      { value: 'APJ Abdul Kalam Technological University' },
      { value: 'Arka Jain University' },
      { value: 'Arni University' },
      { value: 'Arul Anandar College, Madurai ' },
      { value: 'Arunachal University of Studies' },
      { value: 'Arunodaya University' },
      { value: 'Aryabhatta College, Delhi ' },
      { value: 'Aryabhatta Knowledge University' },
      { value: 'Ashoka University' },
      { value: 'Assam Agricultural University' },
      { value: 'Assam Don Bosco University' },
      { value: 'Assam Down Town University' },
      { value: 'Assam Rajiv Gandhi University of Cooperative Management' },
      { value: 'Assam Science and Technology University' },
      { value: 'Assam University' },
      { value: 'Assam Women University' },
      { value: 'Atal Bihari Vajpayee Hindi Vishwavidyalaya' },
      { value: 'Atma Ram Sanatan Dharm College, New Delhi ' },
      { value: 'AURO University' },
      { value: 'Avantika University' },
      { value: 'Avinashilingam University' },
      { value: 'Awadhesh Pratap Singh University' },
      { value: 'Ayush and Health Sciences University of Chhattisgarh' },
      { value: 'Ayya Nadar Janaki Ammal College, Madurai  ' },
      { value: 'Azim Premji University' },
      { value: 'B.S. Abdur Rahman University' },
      { value: 'Baba Farid University of Health Sciences' },
      { value: 'Baba Ghulam Shah Badhshah University' },
      { value: 'Baba Mastnath University' },
      { value: 'Babasaheb Bhimrao Ambedkar Bihar University' },
      { value: 'Babasaheb Bhimrao Ambedkar University' },
      { value: 'Babu Banarasi Das University' },
      { value: 'Baddi University of Emerging Sciences and Technologies' },
      { value: 'BAHRA University' },
      { value: 'Banaras Hindu University' },
      { value: 'Banasthali Vidyapith' },
      { value: 'Banda University of Agriculture and Technology' },
      { value: 'Bangalore University' },
      { value: 'Bankura University' },
      { value: 'Bareilly International University' },
      { value: 'Barkatullah University' },
      { value: 'Bastar Vishwavidyalaya' },
      { value: 'Bengaluru North University' },
      { value: 'Bennett University' },
      { value: 'Berhampur University' },
      { value: 'Bhagat Phool Singh Mahila Vishwavidyalaya' },
      { value: 'Bhagwant University' },
      { value: 'Bhakta Kavi Narsinh Mehta University' },
      { value: 'Bharath Institute of Higher Education and Research' },
      { value: 'Bharathiar University' },
      { value: 'Bharathidasan University' },
      { value: 'Bharati Vidyapeeth University' },
      { value: 'Bhartiya Skill Development University' },
      { value: 'Bhatkhande Music Institute' },
      { value: 'Bhupal Nobles University' },
      { value: 'Bhupendra Narayan Mandal University' },
      { value: 'Bidhan Chandra Krishi Vishwavidyalaya' },
      { value: 'Bihar Agricultural University' },
      { value: 'Biju Patnaik University of Technology' },
      { value: 'Bilaspur Vishwavidyalaya' },
      { value: 'Birla Institute of Technology' },
      { value: 'Birla Institute of Technology and Science' },
      { value: 'Birsa Agricultural University' },
      { value: 'Bishop Moore College, Alappuzha ' },
      { value: 'Bishop Heber College, Tiruchirappalli' },
      { value: 'BLDE University' },
      { value: 'BML Munjal University' },
      { value: 'Bodoland University' },
      { value: 'Brainware University' },
      { value: 'Bundelkhand University' },
      { value: 'C. M. S. College, Kottayam ' },
      { value: 'C.U. Shah University' },
      { value: 'Calorx Teachers University' },
      { value: 'Career Point University' },
      { value: 'Central Agricultural University' },
      { value: 'Central Institute of Fisheries Education' },
      { value: 'Central University of Gujarat' },
      { value: 'Central University of Haryana' },
      { value: 'Central University of Himachal Pradesh' },
      { value: 'Central University of Jammu' },
      { value: 'Central University of Jharkhand' },
      { value: 'Central University of Karnataka' },
      { value: 'Central University of Kashmir' },
      { value: 'Central University of Kerala' },
      { value: 'Central University of Orissa' },
      { value: 'Central University of Punjab' },
      { value: 'Central University of Rajasthan' },
      { value: 'Central University of South Bihar' },
      { value: 'Central University of Tamil Nadu' },
      { value: 'Central University of Tibetan Studies' },
      { value: 'Centurion University of Technology and Management' },
      { value: 'CEPT University' },
      { value: 'Chanakya National Law University' },
      { value: 'Chandigarh University' },
      {
        value: 'Chandra Shekhar Azad University of Agriculture and Technology',
      },
      { value: 'Charotar University of Science and Technology' },
      { value: 'Chaudhary Bansi Lal University' },
      { value: 'Chaudhary Charan Singh Haryana Agricultural University' },
      { value: 'Chaudhary Charan Singh University' },
      { value: 'Chaudhary Devi Lal University' },
      { value: 'Chaudhary Ranbir Singh University' },
      { value: 'Chennai Mathematical Institute' },
      { value: 'Chhatrapati Shahu Ji Maharaj University' },
      { value: 'Chhattisgarh Kamdhenu Vishwavidyalaya' },
      { value: 'Chhattisgarh Swami Vivekananda Technical University' },
      { value: 'Children University' },
      { value: 'Chitkara University' },
      { value: 'Chitkara University' },
      { value: 'Christ College, Thrissur ' },
      { value: 'Christ University' },
      { value: 'Cluster University of Jammu' },
      { value: 'CMJ University' },
      { value: 'CMR University' },
      { value: 'CMS College of Science and Commerce, Coimbatore ' },
      { value: 'Cochin University of Science and Technology' },
      { value: 'College of Vocational Studies, New Delhi ' },
      { value: 'Cooch Behar Panchanan Barma University' },
      { value: 'Cotton University' },
      { value: 'CSK Himachal Pradesh Krishi Vishvavidyalaya' },
      { value: 'D. A. V. College, Chandigarh ' },
      { value: 'Dakshina Bharat Hindi Prachar Sabha' },
      { value: 'Damodaram Sanjivayya National Law University' },
      { value: 'Datta Meghe Institute of Medical Sciences' },
      { value: 'DAV University' },
      { value: 'Davangere University' },
      { value: 'Dyal Singh College, Delhi ' },
      { value: 'Dayalbagh Educational Institute' },
      { value: 'Dayananda Sagar University' },
      { value: 'Deccan College Post-Graduate and Research Institute' },
      { value: 'Deen Dayal Upadhyaya College, New Delhi ' },
      { value: 'Deen Dayal Upadhyay Gorakhpur University' },
      { value: 'Deenbandhu Chhotu Ram University of Science and Technology' },
      { value: 'Delhi Pharmaceutical Sciences and Research University' },
      { value: 'Delhi Technological University' },
      { value: 'Desh Bhagat University' },
      { value: 'Dev Sanskriti Vishwavidyalaya' },
      { value: 'Devi Ahilya Vishwavidyalaya' },
      { value: 'Dharmsinh Desai University' },
      {
        value:
          'Dhirubhai Ambani Institute of Information and Communication Technology',
      },
      { value: 'Diamond Harbour Women University' },
      { value: 'Dibrugarh University' },
      { value: 'DIT University' },
      { value: 'Doon University' },
      { value: 'Dr K.N. Modi University' },
      { value: 'Dr. A.P.J Abdul Kalam University' },
      { value: 'Dr. A.P.J. Abdul Kalam Technical University' },
      { value: 'Dr. B R Ambedkar National Institute of Technology Jalandhar' },
      { value: 'Dr. B.R. Ambedkar University' },
      { value: 'Dr. B.R. Ambedkar University of Social Sciences' },
      { value: 'Dr. Babasaheb Ambedkar Marathwada University' },
      { value: 'Dr. Babasaheb Ambedkar Technological University' },
      { value: 'Dr. Balasaheb Sawant Konkan Krishi Vidyapeeth' },
      { value: 'Dr. Bhimrao Ambedkar University' },
      { value: 'Dr. C.V. Raman University' },
      { value: 'Dr. D.Y. Patil Vidyapeeth' },
      { value: 'Dr. Gafoor Memorial Mes Mampad College, Malappuram ' },
      { value: 'Dr. Hari Singh Gour University' },
      { value: 'Dr. M.G.R. Educational and Research Institute' },
      { value: 'Dr. N. G. P. Arts and Science College, Coimbatore' },
      { value: 'Dr. N.T.R. University of Health Sciences' },
      { value: 'Dr. Panjabrao Deshmukh Krishi Vidyapeeth' },
      { value: 'Dr. Rajendra Prasad Central Agriculture University' },
      { value: 'Dr. Ram Manohar Lohia Avadh University' },
      { value: 'Dr. Ram Manohar Lohiya National Law University' },
      { value: 'Dr. Sarvepalli Radhakrishnan Rajasthan Ayurved University' },
      { value: 'Dr. Shakuntala Misra Rehabilitation University' },
      { value: 'Dr. Vishwanath Karad MIT World Peace University' },
      { value: 'Dr. Y.S. Parmar University of Horticulture and Forestry' },
      { value: 'Dr.Y.S.R. Horticultural University' },
      { value: 'Dravidian University' },
      { value: 'EIILM University' },
      { value: 'Era University' },
      { value: 'Eternal University' },
      { value: 'Ethiraj College for Women, Chennai ' },
      { value: 'Fakir Mohan University' },
      { value: 'Farook College, Kozhikode ' },
      { value: 'Fatima College, Madurai' },
      { value: 'Fatima Mata National College, Kollam ' },
      { value: 'Fergusson College, Pune ' },
      { value: 'Flame University' },
      { value: 'Forest Research Institute' },
      { value: 'G H Raisoni University' },
      { value: 'G.L.S. University' },
      { value: 'Galgotias University' },
      { value: 'Gandhi Institute of Technology and Management' },
      { value: 'Gandhigram Rural University' },
      { value: 'Gangadhar Meher University' },
      { value: 'Ganpat University' },
      { value: 'Garden City University' },
      { value: 'Gargi College, Delhi ' },
      { value: 'Gauhati University' },
      { value: 'Gautam Buddha University' },
      { value: 'Gayatri Vidya Parishad College for Degree and P. G. Courses, Visakapatnam ' },
      { value: 'GD Goenka University' },
      { value: 'Geetanjali University' },
      { value: 'GLA University' },
      { value: 'Glocal University' },
      { value: 'GNA University' },
      { value: 'Goa University' },
      { value: 'Gokhale Institute of Politics and Economics' },
      { value: 'Gondwana University' },
      { value: 'Goswami Ganesh Dutta Sanatan Dharma College, Chandigarh ' },
      { value: 'Government Arts College, Karur ' },
      { value: 'Government Arts College, Coimbatore ' },
      { value: 'Government Arts College, Tiruppur' },
      { value: 'Govind Ballabh Pant University of Agriculture and Technology' },
      { value: 'Govind Guru Tribal University' },
      { value: 'Govt. Post-Graduate College for Girls, Chandigarh' },
      { value: 'Graphic Era Hill University' },
      { value: 'Graphic Era University' },
      { value: 'GSFC University' },
      { value: 'Gujarat Ayurved University' },
      { value: 'Gujarat Forensic Sciences University' },
      { value: 'Gujarat National Law University' },
      { value: 'Gujarat Technological University' },
      { value: 'Gujarat University' },
      { value: 'Gujarat University of Transplantation Sciences' },
      { value: 'Gujarat Vidyapith' },
      { value: 'Gulbarga University' },
      { value: 'Guru Angad Dev Veterinary and Animal Sciences University' },
      { value: 'Guru Ghasidas Vishwavidyalaya' },
      { value: 'Guru Gobind Singh Indraprastha University' },
      { value: 'Guru Jambheshwar University of Science and Technology' },
      { value: 'Guru Kashi University' },
      { value: 'Guru Nanak Dev University' },
      { value: 'Guru Ravidas Ayurved University' },
      { value: 'Gurukul Kangri Vishwavidyalaya' },
      { value: 'Hans Raj College, Delhi ' },
      { value: 'Harcourt Butler Technical University' },
      {
        value: 'Haridev Joshi University of Journalism and Mass Communication',
      },
      { value: 'Haryana Vishwakarma Skill University' },
      { value: 'Hemchandracharya North Gujarat University' },
      { value: 'Hemwati Nandan Bahuguna Garhwal University' },
      { value: 'Hemwati Nandan Bahuguna Medical University' },
      { value: 'Hidayatullah National Law University' },
      { value: 'Himachal Pradesh Technical University' },
      { value: 'Himachal Pradesh University' },
      { value: 'Himalayan Garhwal University' },
      { value: 'Himalayan University' },
      { value: 'Himgiri ZEE University' },
      { value: 'Hindu College, Delhi' },
      { value: 'Hindustan Institute of Technology and Science' },
      { value: 'Holy Cross College, Tiruchirappalli ' },
      { value: 'Homi Bhabha National Institute' },
      { value: 'ICFAI University, Dehradun' },
      { value: 'ICFAI University, Himachal Pradesh' },
      { value: 'ICFAI University, Jaipur' },
      { value: 'ICFAI University, Jharkhand' },
      { value: 'ICFAI University, Meghalaya' },
      { value: 'ICFAI University, Mizora' },
      { value: 'ICFAI University, Nagaland' },
      { value: 'ICFAI University, Raipur' },
      { value: 'ICFAI University, Sikkim' },
      { value: 'ICFAI University, Tripura' },
      { value: 'IEC University' },
      { value: 'IFHE Hyderabad' },
      { value: 'IFTM University' },
      { value: 'IIHMR University' },
      { value: 'IIMT University' },
      { value: 'IMS Unison University' },
      { value: 'Indian Agricultural Research Institute' },
      {
        value:
          'Indian Institute of Engineering Science and Technology, Shibpur',
      },
      { value: 'Indian Institute of Foreign Trade' },
      { value: 'Indian Institute of Information Technology Allahabad' },
      {
        value:
          'Indian Institute of Information Technology and Management Gwalior',
      },
      {
        value:
          'Indian Institute of Information Technology, Design and Manufacturing',
      },
      { value: 'Indian Institute of Information Technology, Guwahati' },
      { value: 'Indian Institute of Information Technology, Kalyani' },
      { value: 'Indian Institute of Information Technology, Kottayam' },
      { value: 'Indian Institute of Information Technology, Lucknow' },
      { value: 'Indian Institute of Information Technology, Manipur' },
      { value: 'Indian Institute of Information Technology, Sri City' },
      { value: 'Indian Institute of Information Technology, Una' },
      { value: 'Indian Institute of Information Technology, Vadodara' },
      { value: 'Indian Institute of Public Health' },
      { value: 'Indian Institute of Science' },
      { value: 'Indian Institute of Science Education and Research, Bhopal' },
      { value: 'Indian Institute of Science Education and Research, Kolkata' },
      { value: 'Indian Institute of Science Education and Research, Mohali' },
      { value: 'Indian Institute of Science Education and Research, Pune' },
      {
        value:
          'Indian Institute of Science Education and Research, Thiruvananthapuram',
      },
      { value: 'Indian Institute of Space Science and Technology' },
      { value: 'Indian Institute of Teacher Education' },
      { value: 'Indian Institute of Technology Bhubaneswar' },
      { value: 'Indian Institute of Technology Bombay' },
      { value: 'Indian Institute of Technology Delhi' },
      { value: 'Indian Institute of Technology Gandhinagar' },
      { value: 'Indian Institute of Technology Guwahati' },
      { value: 'Indian Institute of Technology Hyderabad' },
      { value: 'Indian Institute of Technology Indore' },
      { value: 'Indian Institute of Technology Jodhpur' },
      { value: 'Indian Institute of Technology Kanpur' },
      { value: 'Indian Institute of Technology Kharagpur' },
      { value: 'Indian Institute of Technology Madras' },
      { value: 'Indian Institute of Technology Mandi' },
      { value: 'Indian Institute of Technology Patna' },
      { value: 'Indian Institute of Technology Roorkee' },
      { value: 'Indian Institute of Technology Ropar' },
      { value: 'Indian Institute of Technology, BHU' },
      { value: 'Indian Maritime University' },
      { value: 'Indian School of Mines' },
      { value: 'Indian Statistical Institute' },
      { value: 'Indian Veterinary Research Institute' },
      { value: 'Indira Gandhi Delhi Technical University for Women' },
      { value: 'Indira Gandhi Institute of Development Research' },
      { value: 'Indira Gandhi Institute of Medical Sciences, Sheikhpura' },
      { value: 'Indira Gandhi Krishi Vishwavidyalaya' },
      { value: 'Indira Gandhi National Tribal University' },
      { value: 'Indira Gandhi Technological and Medical Sciences University' },
      { value: 'Indira Gandhi University, Meerpur' },
      { value: 'Indira Kala Sangeet Vishwavidyalaya' },
      { value: 'Indraprastha Institute of Information Technology' },
      { value: 'Indrashil University' },
      { value: 'Indus International University' },
      { value: 'Indus University' },
      { value: 'Institute of Advanced Research' },
      { value: 'Institute of Advanced Studies in Education' },
      { value: 'Institute of Chemical Technology' },
      {
        value:
          'Institute of Infrastructure, Technology, Research and Management',
      },
      { value: 'Integral University' },
      { value: 'International Institute for Population Sciences' },
      { value: 'International Institute of Information Technology Bangalore' },
      {
        value: 'International Institute of Information Technology, Bhubaneswar',
      },
      { value: 'International Institute of Information Technology, Hyderabad' },
      {
        value: 'International Institute of Information Technology, Naya Raipur',
      },
      { value: 'Invertis University' },
      { value: 'ISBM University' },
      { value: 'Islamic University of Science and Technology' },
      { value: 'ITM University Gwalior' },
      { value: 'ITM University Raipur' },
      { value: 'ITM Vocational University' },
      { value: 'Jadavpur University' },
      { value: 'Jagadguru Ramanandacharya Rajasthan Sanskrit University' },
      { value: 'Jagadguru Rambhadracharya Handicapped University' },
      { value: 'Jagadguru Sri Shivarathreeswara University' },
      { value: 'Jagan Nath University' },
      { value: 'Jagannath University' },
      { value: 'Jagran Lakecity University' },
      { value: 'Jai Narain Vyas University' },
      { value: 'Jai Prakash Vishwavidyalaya' },
      { value: 'Jain University' },
      { value: 'Jain Vishva Bharati Institute' },
      { value: 'Jaipur National University' },
      { value: 'Jamal Mohamed College, Tiruchirappalli' },
      { value: 'Jamia Hamdard' },
      { value: 'Jamia Millia Islamia' },
      { value: 'Jananayak Chandrashekhar University' },
      { value: 'Janardan Rai Nagar Rajasthan Vidhyapeeth University' },
      {
        value:
          'Jawaharlal Institute of Postgraduate Medical Education and Research',
      },
      { value: 'Jawaharlal Nehru Architecture and Fine Arts University' },
      { value: 'Jawaharlal Nehru Centre for Advanced Scientific Research' },
      { value: 'Jawaharlal Nehru Krishi Vishwavidyalaya' },
      { value: 'Jawaharlal Nehru Technological University' },
      { value: 'Jawaharlal Nehru Technological University, Anantapur' },
      { value: 'Jawaharlal Nehru Technological University, Kakinada' },
      { value: 'Jawaharlal Nehru University' },
      { value: 'Jayoti Vidyapeeth Women University' },
      { value: 'Jaypee Institute of Information Technology' },
      { value: 'Jaypee University Anoopshahr' },
      { value: 'Jaypee University of Engineering and Technology' },
      { value: 'Jaypee University of Information Technology' },
      { value: 'JECRC University' },
      { value: 'Jharkhand Rai University' },
      { value: 'Jharkhand Raksha Shakti University' },
      { value: 'JIS University' },
      { value: 'Jiwaji University' },
      { value: 'JK Lakshmipat University' },
      { value: 'Jodhpur National University' },
      { value: 'JS University' },
      { value: 'JSS Science and Technology University' },
      { value: 'Junagadh Agricultural University' },
      { value: 'K L University' },
      { value: 'K.K. University' },
      { value: 'K.R. Mangalam University' },
      { value: 'Kadi Sarva Vishwavidyalaya' },
      { value: 'Kakatiya University' },
      { value: 'Kalasalingam University' },
      { value: 'Kalinga University' },
      { value: 'Kamdhenu University' },
      { value: 'Kameshwar Singh Darbhanga Sanskrit University' },
      { value: 'Kannada University' },
      { value: 'Kannur University' },
      { value: 'Karnatak University' },
      { value: 'Karnataka Janapada Vishwavidyalaya' },
      { value: 'Karnataka Sanskrit University' },
      { value: 'Karnataka State Law University' },
      {
        value: 'Karnataka State Rural Development and Panchayat Raj University',
      },
      { value: 'Karnataka State Women University' },
      {
        value: 'Karnataka Veterinary, Animal and Fisheries Sciences University',
      },
      { value: 'Karnavati University' },
      { value: 'Karpagam Academy of Higher Education' },
      { value: 'Karunya University' },
      { value: 'Kavi Kulguru Kalidas Sanskrit Vishwavidyalaya' },
      { value: 'Kazi Nazrul University' },
      { value: 'Kaziranga University' },
      { value: 'Kerala Agricultural University' },
      { value: 'Kerala Kalamandalam' },
      { value: 'Kerala University of Fisheries and Ocean Studies' },
      { value: 'Kerala University of Health Sciences' },
      { value: 'Kerala Veterinary and Animal Sciences University' },
      { value: 'Keshav Mahavidyalya, Delhi ' },
      { value: 'Khallikote University' },
      { value: 'Khalsa University' },
      { value: 'Khwaja Moinuddin Chishti Urdu, Arabi-Farsi University' },
      { value: 'KIIT University' },
      { value: 'King George Medical University' },
      { value: 'Kirori Mal College, Delhi ' },
      { value: 'KLE Technological University' },
      { value: 'KLE University' },
      { value: 'Kolhan University' },
      { value: 'Kongu Arts & Science College, Erode ' },
      { value: 'Kongunadu Arts & Science College, Coimbatore' },
      { value: 'Krantiguru Shyamji Krishna Verma Kachchh University' },
      { value: 'Krishna Institute of Medical Sciences' },
      { value: 'Krishna University' },
      { value: 'KSGH Music and Performing Arts University' },
      { value: 'Kumar Bhaskar Varma Sanskrit and Ancient Studies University' },
      { value: 'Kumaun University' },
      { value: 'Kuriakose Gregorios College, Kottayam ' },
      { value: 'Kurukshetra University' },
      { value: 'Kushabhau Thakre Patrakarita Avam Jansanchar University' },
      { value: 'Kuvempu University' },
      { value: 'Lady Doak College, Madurai ' },
      { value: 'Lady Irwin College, Delhi ' },
      { value: 'Lady Shri Ram College for Women, New Delhi' },
      { value: 'Lakshmibai National Institute of Physical Education' },
      { value: 'Lakulish Yoga University' },
      { value: 'Lala Lajpat Rai University of Veterinary and Animal Sciences' },
      { value: 'Lalit Narayan Mithila University' },
      { value: 'Lingaya University' },
      { value: 'LNCT University' },
      { value: 'Loreto College, Calcutta ' },
      { value: 'Lovely Professional University' },
      { value: 'Loyola College, Chennai' },
      { value: 'M.J.P. Rohilkhand University' },
      { value: 'M.S. Ramaiah University of Applied Sciences' },
      { value: 'Madan Mohan Malaviya University of Technology' },
      { value: 'Madhav University' },
      { value: 'Madras Christian College, Chennai ' },
      { value: 'Madurai Kamaraj University' },
      { value: 'Magadh University' },
      { value: 'Mahapurusha Srimanta Sankaradeva Viswavidyalaya' },
      { value: 'Maharaja Agrasen College, Delhi ' },
      { value: 'Maharaja Agrasen University' },
      { value: 'Maharaja Bir Bikram University' },
      { value: 'Maharaja Chhatrasal Bundelkhand University' },
      { value: 'Maharaja Ganga Singh University' },
      { value: 'Maharaja Krishnakumarsinhji Bhavnagar University' },
      { value: 'Maharaja Ranjit Singh Punjab Technical University' },
      { value: 'Maharaja Surajmal Brij University' },
      { value: 'Maharana Pratap University of Agriculture and Technology' },
      { value: 'Maharashtra Animal and Fishery Sciences University' },
      { value: 'Maharashtra National Law University, Aurangabad' },
      { value: 'Maharashtra National Law University, Mumbai' },
      { value: 'Maharashtra National Law University, Nagpur' },
      { value: 'Maharashtra University of Health Sciences' },
      { value: 'Maharishi Arvind University, Jaipur' },
      { value: 'Maharishi Dayanand University' },
      { value: 'Maharishi Mahesh Yogi Vedic Vishwavidyalaya' },
      { value: 'Maharishi Markandeshwar University, Mullana' },
      { value: 'Maharishi Markandeshwar University, Sadopur' },
      { value: 'Maharishi Markandeshwar University, Solan' },
      { value: 'Maharishi University' },
      { value: 'Maharishi University of Management and Technology' },
      { value: 'Maharshi Dayanand Saraswati University' },
      { value: 'Maharshi Panini Sanskrit Vishwavidyalaya' },
      { value: 'Mahatma Gandhi Antarrashtriya Hindi Vishwavidyalaya' },
      { value: 'Mahatma Gandhi Central University, Motihari' },
      { value: 'Mahatma Gandhi Chitrakoot Gramoday Vishwavidyalaya' },
      { value: 'Mahatma Gandhi College, Thiruvananthapuram ' },
      { value: 'Mahatma Gandhi Kashi Vidyapeeth' },
      { value: 'Mahatma Gandhi University' },
      { value: 'Mahatma Gandhi University of Medical Sciences and Technology' },
      { value: 'Mahatma Gandhi University, Meghalaya' },
      { value: 'Mahatma Gandhi University, Nalgonda' },
      { value: 'Mahatma Jyoti Rao Phoole University' },
      { value: 'Mahatma Phule Krishi Vidyapeeth' },
      { value: 'Mahendra Arts & Science College, Namakkal ' },
      { value: 'Maitreyi College, New Delhi ' },
      { value: 'Makhanlal Chaturvedi Rashtriya Patrakarita Vishwavidyalaya' },
      { value: 'Malaviya National Institute of Technology, Jaipur' },
      { value: 'Malwanchal University' },
      { value: 'Manav Bharti University' },
      { value: 'Manav Rachna International Institute of Research and Studies' },
      { value: 'Manav Rachna University' },
      { value: 'Mandsaur University' },
      { value: 'Mangalayatan University' },
      { value: 'Mangalore University' },
      { value: 'Manipal University' },
      { value: 'Manipur Technical University' },
      { value: 'Manipur University' },
      { value: 'Manipur University of Culture' },
      { value: 'Manonmaniam Sundaranar University' },
      { value: 'Miranda House, Delhi' },
      { value: 'Mar Ivanios College, Thiruvananthapuram ' },
      { value: 'Marian College, Kuttikanam ' },
      { value: 'Martin Luther Christian University' },
      { value: 'Marwadi University' },
      { value: 'MATS University' },
      { value: 'Maulana Abul Kalam Azad University of Technology' },
      { value: 'Maulana Azad National Institute of Technology' },
      { value: 'Maulana Azad National Urdu University' },
      { value: 'Maulana Azad University, Jodhpur' },
      { value: 'Maulana Mazharul Haque Arabic and Persian University' },
      { value: 'Medi-Caps University' },
      { value: 'Meenakshi Academy of Higher Education and Research' },
      { value: 'Mewar University' },
      { value: 'MGM Institute of Health Sciences' },
      { value: 'MIT Art Design and Technology University' },
      { value: 'Mizoram University' },
      { value: 'Mody University of Science and Technology' },
      { value: 'Mohammad Ali Jauhar University' },
      { value: 'Mohanlal Sukhadia University' },
      { value: 'Monad University' },
      { value: 'Mother Teresa Women University' },
      { value: 'Motherhood University' },
      { value: 'Motilal Nehru National Institute of Technology' },
      { value: 'MVN University' },
      { value: 'Nagaland University' },
      { value: 'Nalanda University' },
      { value: 'NALSAR University of Law' },
      { value: 'Nanaji Deshmukh Veterinary Science University' },
      { value: 'Narendra Dev University of Agriculture and Technology' },
      { value: 'Narsee Monjee Institute of Management and Higher Studies' },
      { value: 'National College, Tiruchirapalli ' },
      { value: 'National Dairy Research Institute' },
      { value: 'National Institute of Design' },
      { value: 'National Institute of Fashion Technology' },
      {
        value:
          'National Institute of Food Technology Entrepreneurship and Management',
      },
      { value: 'National Institute of Mental Health and Neuro Sciences' },
      {
        value:
          'National Institute of Pharmaceutical Education and Research, Ahmedabad',
      },
      {
        value:
          'National Institute of Pharmaceutical Education and Research, Guwahati',
      },
      {
        value:
          'National Institute of Pharmaceutical Education and Research, Hajipur',
      },
      {
        value:
          'National Institute of Pharmaceutical Education and Research, Hyderabad',
      },
      {
        value:
          'National Institute of Pharmaceutical Education and Research, Kolkata',
      },
      {
        value:
          'National Institute of Pharmaceutical Education and Research, Mohali',
      },
      {
        value:
          'National Institute of Pharmaceutical Education and Research, Rae Bareli',
      },
      { value: 'National Institute of Technology, Agartala' },
      { value: 'National Institute of Technology, Arunachal Pradesh' },
      { value: 'National Institute of Technology, Calicut' },
      { value: 'National Institute of Technology, Delhi' },
      { value: 'National Institute of Technology, Durgapur' },
      { value: 'National Institute of Technology, Goa' },
      { value: 'National Institute of Technology, Hamirpur' },
      { value: 'National Institute of Technology, Jamshedpur' },
      { value: 'National Institute of Technology, Karnataka' },
      { value: 'National Institute of Technology, Kurukshetra' },
      { value: 'National Institute of Technology, Manipur' },
      { value: 'National Institute of Technology, Meghalaya' },
      { value: 'National Institute of Technology, Mizoram' },
      { value: 'National Institute of Technology, Nagaland' },
      { value: 'National Institute of Technology, Patna' },
      { value: 'National Institute of Technology, Puducherry' },
      { value: 'National Institute of Technology, Raipur' },
      { value: 'National Institute of Technology, Rourkela' },
      { value: 'National Institute of Technology, Sikkim' },
      { value: 'National Institute of Technology, Silchar' },
      { value: 'National Institute of Technology, Srinagar' },
      { value: 'National Institute of Technology, Tiruchirappalli' },
      { value: 'National Institute of Technology, Uttarakhand' },
      { value: 'National Institute of Technology, Warangal' },
      { value: 'National Law Institute University' },
      { value: 'National Law School of India University' },
      { value: 'National Law University' },
      { value: 'National Law University and Judicial Academy' },
      { value: 'National Law University, Jodhpur' },
      { value: 'National Law University, Orissa' },
      {
        value: 'National University of Educational Planning and Administration',
      },
      { value: 'National University of Study and Research in Law' },
      { value: 'Nava Nalanda Mahavihara' },
      { value: 'Navrachana University' },
      { value: 'Navsari Agricultural University' },
      { value: 'Nehru Gram Bharati Vishwavidyalaya' },
      { value: 'NIILM University' },
      { value: 'NIIT University' },
      { value: 'Nilamber-Pitamber University' },
      { value: 'NIMS University' },
      { value: 'Nirma University of Science and Technology' },
      { value: 'Nirmalagiri College, Kannur' },
      { value: 'NITTE University' },
      { value: 'Nizam Institute of Medical Sciences' },
      { value: 'Noida International University' },
      { value: 'North East Frontier Technical University' },
      { value: 'North Eastern Hill University' },
      { value: 'North Eastern Regional Institute of Science and Technology' },
      { value: 'North Maharashtra University' },
      { value: 'North Orissa University' },
      { value: 'O.P. Jindal Global University' },
      { value: 'O.P. Jindal University' },
      { value: 'OPJS University' },
      { value: 'Oriental University' },
      { value: 'Orissa University of Agriculture and Technology' },
      { value: 'Osmania University' },
      { value: 'Other' },
      { value: 'P P Savani University' },
      { value: 'P.K. University' },
      { value: 'Pacific Medical University' },
      { value: 'Pacific University, India' },
      { value: 'Padmashree Dr. D.Y. Patil Vidyapith' },
      { value: 'Palamuru University' },
      { value: 'Pandit Deendayal Petroleum University' },
      { value: 'Pandit Deendayal Upadhyaya Shekhawati University' },
      { value: 'Pandit Ravishankar Shukla University' },
      { value: 'Panjab University' },
      { value: 'Parul University' },
      { value: 'Patna University' },
      { value: 'PDM University' },
      {
        value:
          'PDPM Indian Institute of Information Technology, Design and Manufacturing',
      },
      { value: 'PEC University of Technology' },

      { value: 'People University' },
      { value: 'Periyar Maniammai University' },
      { value: 'Periyar University' },
      { value: 'PES University' },
      { value: 'Plastindia International University' },
      { value: 'Pondicherry University' },
      { value: 'Ponnaiyan Ramajayam Institute of Science and Technology' },
      { value: 'Poornima University' },
      { value: 'Post Graduate Institute of Medical Education and Research' },
      { value: 'Potti Sreeramulu Telugu University' },
      { value: 'Pragyan International University' },
      { value: 'Pratap University' },
      { value: 'Pravara Institute of Medical Sciences' },
      { value: 'Presidency University' },
      { value: 'Presidency College, Chennai' },
      {
        value: 'Professor Jayashankar Telangana State Agricultural University',
      },
      { value: 'PSG College of Arts and Science, Coimbatore ' },
      { value: 'PSGR Krishnammal College for Women, Coimbatore ' },
      { value: 'Pt. Bhagwat Dayal Sharma University of Health Sciences' },
      { value: 'Punjab Agricultural University' },
      { value: 'Punjab Technical University' },
      { value: 'Punjabi University' },
      { value: 'Quantum University' },
      { value: 'Queen Mary`s College, Chennai ' },
      { value: 'Rabindra Bharati University' },
      { value: 'Raffles University' },
      { value: 'Rai Technology University' },
      { value: 'Rai University' },
      { value: 'Raiganj University' },
      { value: 'Raj Rishi Bharthari Matsya University' },
      { value: 'Raja Mansingh Tomar Music and Arts University' },
      { value: 'Rajasthan Technical University Kota' },
      { value: 'Rajasthan University of Health Sciences' },
      { value: 'Rajasthan University of Veterinary and Animal Sciences' },
      { value: 'Rajiv Gandhi Institute of Petroleum Technology' },
      { value: 'Rajiv Gandhi National Aviation University' },
      { value: 'Rajiv Gandhi National Institute of Youth Development' },
      { value: 'Rajiv Gandhi National University of Law' },
      { value: 'Rajiv Gandhi Proudyogiki Vishwavidyalaya' },
      { value: 'Rajiv Gandhi University' },
      { value: 'Rajiv Gandhi University of Health Sciences' },
      { value: 'Rajiv Gandhi University of Knowledge Technologies' },
      { value: 'Rajmata Vijayaraje Scindia Krishi Vishwavidyalaya' },
      { value: 'Raksha Shakti University' },
      { value: 'Rama Devi Women University' },
      { value: 'Rama University' },
      { value: 'Ramakrishna Mission Residential College, Kolkata ' },
      { value: 'Rama Krishna Mission Vivekananda Centenary College, Rahara ' },
      { value: 'Ramakrishna Mission Vivekananda University' },
      { value: 'Ramakrishna Mission Vidyamandira, Howrah ' },
      { value: 'Ramanujan College, New Delhi ' },
      { value: 'Ranchi University' },
      { value: 'Rani Channamma University, Belagavi' },
      { value: 'Rani Durgavati Vishwavidyalaya' },
      { value: 'Rani Lakshmi Bai Central Agricultural University' },
      { value: 'Ras Bihari Bose Subharti University' },
      { value: 'Rashtrasant Tukadoji Maharaj Nagpur University' },
      { value: 'Rashtriya Sanskrit Sansthan University' },
      { value: 'Rashtriya Sanskrit Vidyapeetha' },
      { value: 'Rathinam College of Arts and Science, Coimbatore' },
      { value: 'Ravenshaw University' },
      { value: 'Rayalaseema University' },
      { value: 'Rayat-Bahra University' },
      { value: 'REVA University' },
      { value: 'RIMT University' },
      { value: 'RK University' },
      { value: 'RKDF University' },
      { value: 'S. B. College, Kottayam ' },
      { value: 'Sacred Heart College, Ernakulam ' },
      { value: 'Sai Nath University' },
      { value: 'Sai Tirupati University' },
      {
        value:
          'Sam Higginbottom Institute of Agriculture, Technology and Sciences',
      },
      { value: 'Sambalpur University' },
      { value: 'Sampurnanand Sanskrit Vishvavidyalaya' },
      { value: 'Sanchi University of Buddhist-Indic Studies' },
      { value: 'Sandip University' },
      { value: 'Sandip University, Sijoul' },
      { value: 'Sangai International University' },
      { value: 'Sangam University' },
      { value: 'Sanjay Gandhi Post Graduate Institute of Medical Sciences' },
      { value: 'Sanjay Ghodawat University' },
      { value: 'Sankalchand Patel University' },
      { value: 'Sanskriti University' },
      { value: 'Sant Baba Bhag Singh University' },
      { value: 'Sant Gadge Baba Amravati University' },
      { value: 'Sant Longowal Institute of Engineering and Technology' },
      { value: 'Santosh University' },
      { value: 'Sardar Patel University' },
      {
        value:
          'Sardar Patel University of Police, Security and Criminal Justice',
      },
      { value: 'Sardar Vallabhbhai National Institute of Technology, Surat' },
      {
        value:
          'Sardar Vallabhbhai Patel University of Agriculture and Technology',
      },
      { value: 'Sardarkrushinagar Dantiwada Agricultural University' },
      { value: 'Sarguja University' },
      { value: 'Sarla Birla University' },
      { value: 'Sarvepalli Radhakrishnan University' },
      { value: 'SASTRA University' },
      { value: 'Satavahana University' },
      { value: 'Sathyabama University' },
      { value: 'Saurashtra University' },
      { value: 'Saveetha University' },
      { value: 'Savitribai Phule Pune University' },
      { value: 'School of Planning and Architecture, Bhopal' },
      { value: 'School of Planning and Architecture, Delhi' },
      { value: 'School of Planning and Architecture, Vijayawada' },
      { value: 'Scott Christian College, Nagercoil' },
      { value: 'Seacom Skills University' },
      { value: 'Shaheed Rajguru College of Applied Sciences for Women, Delhi ' },
      { value: 'Sharda University' },
      { value: 'Sharnbasva University' },
      {
        value:
          'Sher-e-Kashmir University of Agricultural Sciences and Technology of Jammu',
      },
      {
        value:
          'Sher-e-Kashmir University of Agricultural Sciences and Technology of Kashmir',
      },
      { value: 'Sher-i-Kashmir Institute of Medical Sciences' },
      { value: 'Shiv Nadar University' },
      { value: 'Shivaji College, Delhi' },
      { value: 'Shivaji University' },
      { value: 'Shobhit University' },
      { value: 'Shoolini University of Biotechnology and Management Sciences' },
      { value: 'Shree Guru Gobind Singh Tricentenary University' },
      { value: 'Shree Somnath Sanskrit University' },
      { value: 'Shreemati Nathibai Damodar Thackersey Women University' },
      { value: 'Shri Govind Guru University' },
      { value: 'Shri Guru Ram Rai Education Mission' },
      { value: 'Shri Guru Ram Rai University' },
      { value: 'Shri Jagannath Sanskrit Vishvavidyalaya' },
      { value: 'Shri Jagdishprasad Jhabrmal Tibrewala University' },
      { value: 'Shri Lal Bahadur Shastri Rashtriya Sanskrit Vidyapeetha' },
      { value: 'Shri Mata Vaishno Devi University' },
      { value: 'Shri Ramswaroop Memorial University' },
      { value: 'Shri Vaishnav Vidyapeeth Vishwavidyalaya' },
      { value: 'Shri Venkateshwara University' },
      { value: 'Shridhar University' },
      { value: 'Shyam Lal College, Delhi' },
      { value: 'Siddharth University' },
      { value: 'Sidho Kanho Birsha University' },
      { value: 'Sido Kanhu Murmu University' },
      { value: 'Sikkim Manipal University' },
      { value: 'Sikkim University' },
      { value: 'Siksha O Anusandhan University' },
      { value: 'Silver Jubilee Degree College, Kurnool ' },
      { value: 'Singhania University' },
      { value: 'Sir Padampat Singhania University' },
      { value: 'South Asian University' },
      { value: 'Spicer Adventist University' },
      {
        value:
          'Sree Chitra Thirunal Institute of Medical Sciences and Technology',
      },
      { value: 'Sree Sankaracharya University of Sanskrit' },
      { value: 'Sri Balaji Vidyapeeth' },
      { value: 'Sri Chandrasekharendra Saraswathi Viswa Mahavidyalaya' },
      { value: 'Sri Dev Suman Uttarakhand University' },
      { value: 'Sri Devaraj Urs Academy of Higher Education and Research' },
      { value: 'Sri Guru Granth Sahib World University' },
      { value: 'Sri Guru Tegh Bahadur Khalsa College, Delhi ' },
      { value: 'Sri Guru Ram Das University of Health Sciences' },
      { value: 'Sri Konda Laxman Telangana State Horticultural University' },
      { value: 'Sri Krishna Arts and Science College, Coimbatore' },
      { value: 'Sri Krishnadevaraya University' },
      { value: 'Sri Meenakshi Government College for Women, Madurai ' },
      { value: 'Sri Padmavati Mahila Visvavidyalayam' },
      { value: 'Sri Ramachandra University' },
      { value: 'Sri Ramakrishna Mission Vidyalaya College of Arts & Science, Coimbatore' },
      { value: 'Sri Sai University' },
      { value: 'Sri Sathya Sai Institute of Higher Learning' },
      { value: 'Sri Satya Sai University of Technology and Medical Sciences' },
      { value: 'Sri Siddhartha Academy of Higher Education' },
      { value: 'Sri Sri University' },
      { value: 'Sri Venkateswara College, Delhi ' },
      { value: 'Sri Venkateswara Institute of Medical Sciences' },
      { value: 'Sri Venkateswara University' },
      { value: 'Sri Venkateswara Vedic University' },
      { value: 'Sri Venkateswara Veterinary University' },
      { value: 'Srimanta Sankaradeva University of Health Sciences' },
      { value: 'Srinivas University' },
      { value: 'SRM Institute of Science and Technology' },
      { value: 'SRM University Haryana' },
      { value: 'SRM University, Sikkim' },
      { value: 'St. Aloysius College, Mangalore ' },
      { value: 'St. Joseph University' },
      { value: 'St. Joseph`s Arts & Science College, Bengaluru ' },
      { value: 'St. Joseph`s College, Calicut' },
      { value: "St. Joseph's College, Thrissur " },
      { value: 'St. Joseph`s College, Tiruchirappalli' },
      { value: 'St. Peter University' },
      { value: 'St. Stephen`s College, Delhi' },
      { value: 'St. Teresa`s College, Ernakulam ' },
      { value: 'St. Thomas College, Thrissur ' },
      { value: 'St. Xavier University' },
      { value: 'St. Xavier`s College, Ahmedabad' },
      { value: 'St. Xavier`s College, Kolkata ' },
      { value: 'St. Xavier`s College, Mumbai ' },
      { value: "St.Xavier's College, Palayamkottai " },
      { value: 'Starex University' },
      { value: 'State University of Performing and Visual Arts' },
      { value: 'Stella Maris College for Women, Chennai  ' },
      { value: 'Suamandeep Vidyapeeth' },
      { value: 'Sunrise University' },
      { value: 'Suresh Gyan Vihar University' },
      { value: 'Swami Keshwanand Rajasthan Agricultural University' },
      { value: 'Swami Rama Himalayan University' },
      { value: 'Swami Ramanand Teerth Marathwada University' },
      { value: 'Swami Vivekanand Subharti University' },
      { value: 'Swami Vivekanand University' },
      { value: 'Swami Vivekananda Yoga Anusandhana Samsthana' },
      { value: 'Swarnim Gujarat Sports University' },
      { value: 'Swarnim Startup and Innovation University' },
      { value: 'Symbiosis International University' },
      { value: 'Symbiosis University of Applied Sciences' },
      { value: 'T. K. M. College of Arts and Science, Kollam ' },
      { value: 'Tamil Nadu Agricultural University' },
      { value: 'Tamil Nadu Dr Ambedkar Law University' },
      { value: 'Tamil Nadu Dr. M.G.R.Medical University' },
      { value: 'Tamil Nadu Fisheries University' },
      { value: 'Tamil Nadu Music and Fine Arts University' },
      { value: 'Tamil Nadu National Law School' },
      { value: 'Tamil Nadu Physical Education and Sports University' },
      { value: 'Tamil Nadu Teacher Education University' },
      { value: 'Tamil Nadu Veterinary and Animal Sciences University' },
      { value: 'Tamil University' },
      { value: 'Tantia University' },
      { value: 'Tata Institute of Fundamental Research' },
      { value: 'Tata Institute of Social Sciences' },
      { value: 'TeamLease Skills University' },
      { value: 'Techno India University' },
      { value: 'Teerthanker Mahaveer University' },
      { value: 'Telangana University' },
      { value: 'TERI University' },
      { value: 'Tezpur University' },
      { value: 'Thapar Institute of Engineering and Technology' },
      { value: 'The American College, Madurai ' },
      { value: 'The English and Foreign Languages University' },
      { value: 'The IIS University' },
      { value: 'The Indian Law Institute' },
      { value: 'The LNM Institute of Information Technology' },
      { value: 'The Maharaja Sayajirao University of Baroda' },
      { value: 'The National University of Advanced Legal Studies' },
      { value: 'The Neotia University' },
      { value: 'The Northcap University' },
      { value: 'The Sanskrit College and University' },
      { value: 'The West Bengal National University of Juridical Sciences' },
      { value: 'Thiagarajar College, Madurai ' },
      { value: 'Thiruvalluvar University' },
      { value: 'Thunchath Ezhuthachan Malayalam University' },
      { value: 'Tilak Maharashtra Vidyapeeth' },
      { value: 'Tilka Manjhi Bhagalpur University' },
      { value: 'TransDisciplinary University' },
      { value: 'Tripura University' },
      { value: 'Tumkur University' },
      {
        value:
          'U.P. Pandit Deen Dayal Upadhyaya Pashu Chikitsa Vigyan Vishwavidyalaya Evam Go-Anusandhan Sansthan',
      },
      { value: 'UKA Tarsadia University' },
      {
        value:
          'University of Agricultural and Horticultural Sciences, Shivamogga',
      },
      { value: 'University College, Thiruvananthapuram' },
      { value: 'University of Agricultural Sciences, Bangalore' },
      { value: 'University of Agricultural Sciences, Dharwad' },
      { value: 'University of Agricultural Sciences, Raichur' },
      { value: 'University of Allahabad' },
      { value: 'University of Burdwan' },
      { value: 'University of Calcutta' },
      { value: 'University of Calicut' },
      { value: 'University of Delhi' },
      { value: 'University of Engineering and Management, Kolkata' },
      { value: 'University of Gour Banga' },
      { value: 'University of Horticultural Sciences, Bagalkot' },
      { value: 'University of Hyderabad' },
      { value: 'University of Jammu' },
      { value: 'University of Kalyani' },
      { value: 'University of Kashmir' },
      { value: 'University of Kerala' },
      { value: 'University of Kota' },
      { value: 'University of Lucknow' },
      { value: 'University of Madras' },
      { value: 'University of Mumbai' },
      { value: 'University of Mysore' },
      { value: 'University of North Bengal' },
      { value: 'University of Patanjali' },
      { value: 'University of Petroleum and Energy Studies' },
      { value: 'University of Rajasthan' },
      { value: 'University of Science and Technology, Meghalaya' },
      { value: 'University of Solapur' },
      { value: 'University of Technology' },
      { value: 'University of Technology and Management' },
      { value: 'Usha Martin University' },
      { value: 'Utkal University' },
      { value: 'Utkal University of Culture' },
      { value: 'Uttar Banga Krishi Viswavidyalaya' },
      { value: 'Uttar Pradesh University of Medical Sciences' },
      { value: 'Uttarakhand Aawasiya Vishwavidyalaya' },
      { value: 'Uttarakhand Ayurved University' },
      { value: 'Uttarakhand Technical University' },
      { value: 'Uttarakhand University of Horticulture and Forestry' },
      { value: 'Uttaranchal Sanskrit University' },
      { value: 'Uttaranchal University' },
      { value: 'V. V. Vanniaperumal College for Women, Virudhnagar ' },
      { value: 'Vasantrao Naik Marathwada Krishi Vidyapeeth' },
      { value: 'Veer Bahadur Singh Purvanchal University' },
      { value: 'Veer Kunwar Singh University' },
      { value: 'Veer Narmad South Gujarat University' },
      { value: 'Veer Surendra Sai University of Technology' },
      { value: 'Vel Tech Dr.RR and Dr.SR Technical University' },
      { value: 'Vellalar College for Women, Erode ' },
      { value: 'Vels University' },
      { value: 'Vidyasagar University' },
      { value: 'Vignan University' },
      { value: 'Vijayanagara Sri Krishnadevaraya University' },
      { value: 'Vikram University' },
      { value: 'Vikrama Simhapuri University' },
      { value: 'Vimala College, Thrissur ' },
      { value: 'Vinayaka Missions Sikkim University' },
      { value: 'Vinayaka Missions University' },
      { value: 'Vinoba Bhave University' },
      { value: 'Virudhunagar Hindu Nadars Senthikumara Nadar College, Virudhnagar' },
      { value: 'Vishwakarma University' },
      { value: 'Visva-Bharati University' },
      { value: 'Visvesvaraya National Institute of Technology' },
      { value: 'Visvesvaraya Technological University' },
      { value: 'VIT Bhopal University' },
      { value: 'VIT University' },
      { value: 'Vivekananda Global University' },
      { value: 'West Bengal State University' },
      { value: 'West Bengal University of Animal and Fishery Sciences' },
      { value: 'West Bengal University of Health Sciences' },
      {
        value:
          'West Bengal University of Teachers Training, Education Planning and Administration',
      },
      { value: 'William Carey University, India' },
      { value: 'William Carey University, Meghalaya' },
      { value: 'Women`s Christian College, Chennai ' },
      { value: 'Women`s Christian College, Nagercoil ' },
      { value: 'Xavier University Bhubaneswar' },
      { value: 'YBN University' },
      { value: 'Yenepoya University' },
      { value: 'YMCA University of Science and Technology' },
      { value: 'Yogi Vemana University' },
      { value: 'Other' }
    ];
    this.courseTypes = [
      { value: 'PART TIME' },
      { value: 'FULL TIME' },
      { value: 'CORRESPONDING' },
    ];
  }
  userTypeFind(userType) {
    if (userType === 'Fresher') {
      this.fresher = true;
    } else {
      this.fresher = false;
    }
  }
  qualificationChange(evt, i) {
    console.log(evt.target.value, i);
    this.disableLinks(
      this.qualificationsArray[0].indexOf({ value: evt.target.value }),
      i
    );
    evt.target.value === 'Below 10th' ? this.clearForm() : console.log('');
    if (evt.target.value === '10th' || '12th') {
    }
  }
  addfieldsFormGroup() {
    const newFields = this.formBuilder.group({
      qualification: ['', Validators.required],
      course: ['', Validators.required],
      specialization: ['', Validators.required],
      college: ['', Validators.required],
      course_type: ['', Validators.required],
      passing_year: ['', Validators.required],
    });
    this.educations.push(newFields);
    this.disableLink = false;
  }
  get educations() {
    return this.signupEducationForm.get('education') as FormArray;
  }
  deletePhone(i) {
    this.educations.removeAt(i);
  }
  onFormSubmit() {
    console.log(this.educations.controls);
    console.log(
      this.educations.controls[this.educations.controls.length - 1].value
        .qualification
    );
    // this.router.navigate(['/candidate/dashboard']);
    console.log(this.items);
    for (let i = 0; i < this.educations.controls.length; i++) {
      if (this.educations.controls[i].value.qualification === '') {
        i++;
      } else {
        this.education.push(this.educations.controls[i].value);
      }
    }
    for (let i = 0; i < this.items.length; i++) {
      this.skills.push(this.items[i].display);
    }
    console.log('education', this.education);
    this.updateEducation();
  }
  disableLinks(i, j) {
    if (
      this.educations.controls[this.educations.controls.length - 1].value
        .qualification === ''
    ) {
      this.disableLink = false;
    } else {
      if (
        this.educations.controls[this.educations.controls.length - 1].value
          .qualification === 'Doctrate PHD'
      ) {
        this.addfieldsFormGroup();
        this.disableLink = false;
        this.changeQualifuctions(1, j);
      } else if (
        this.educations.controls[this.educations.controls.length - 1].value
          .qualification === 'Masters/Post Graduation'
      ) {
        this.addfieldsFormGroup();
        this.disableLink = false;
        this.changeQualifuctions(2, j);
      } else if (
        this.educations.controls[this.educations.controls.length - 1].value
          .qualification === 'Graduation/Diploma'
      ) {
        this.changeQualifuctions(3, j);
        this.disableLink = false;
        this.addfieldsFormGroup();
      } else if (
        this.educations.controls[this.educations.controls.length - 1].value
          .qualification === '12th'
      ) {
        // this.addfieldsFormGroup();
        this.disableLink = true;
        this.changeQualifuctions(4, j);
      } else if (
        this.educations.controls[this.educations.controls.length - 1].value
          .qualification === '10th'
      ) {
        this.disableLink = false;
      } else if (
        this.educations.controls[this.educations.controls.length - 1].value
          .qualification === 'Below 10th'
      ) {
        this.disableLink = false;
        this.clearForm();
      } else {
        this.disableLink = false;
      }
    }
  }
  changeQualifuctions(i, j) {
    console.log(i, j);
    this.below10 = true;
    const qualificationsNewArray = this.qualificationsArray[0].slice(i, 5);
    console.log(qualificationsNewArray);
    this.qualificationsArray.push(qualificationsNewArray);
  }
  clearForm() {
    console.log('reseting Form');
    this.below10 = false;
    this.disableLink = false;
    for (let i = 1; i < this.educations.controls.length; i++) {
      console.log(i);
      this.educations.removeAt(i);
    }
    console.log(this.educations.controls);
  }
  updateEducation() {
    const form = {
      education: this.education,
      kills: this.skills,
    };
    this.appService
      .editprofileApplicant(form, this.uniqueId)
      .subscribe(data => {
        console.log(data);
        this.toaster.success(data.responseMessage);
        localStorage.setItem('userID', JSON.stringify(this.uniqueId));
        this.router.navigate(['/candidateHeader/dashboard']);
      });
  }
}
